# Generated by Django 5.2.3 on 2025-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
